
- name: Docker installing
  hosts: prod_servers
  become: yes

  tasks:
    - name: Installing Docker
      shell: amazon-linux-extras install -y docker

    - name: Installing Docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: change mod
      shell: chmod +x /usr/local/bin/docker-compose

    - name: create link
      shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Start Docker engine
      service: name=docker state=started

    - name: Installing Git
      yum: name=git state=latest

    - name: Adding repo
      copy: src=psql12_repo dest=/etc/yum.repos.d/pgdg.repo

    - name: make cache
      shell: yum makecache

    - name: installig Postgresql12
      yum: name=postgresql12 state=installed

    - name: Create env file
      copy: src=.env dest=/var/.env

    - name: Create .pgpass
      copy: src=.pgpass dest=/home/ec2-user/ mode=600

    - name: change owner .pgpass
      shell: chown ec2-user:ec2-user /home/ec2-user/.pgpass

    - name: copy ssh key for git
      copy: src=/var/lib/jenkins/.ssh/id_rsa dest=/home/.ssh/id_rsa mode=400

    - name: copy known_hosts
      copy: src=/var/lib/jenkins/.ssh/known_hosts dest=/home/.ssh/known_hosts

    - name: chenge owner for key
      shell: chown ec2-user:ec2-user /home/.ssh/id_rsa /home/.ssh/known_hosts
