- name: Provision wgtail application
  hosts: prod_servers

  tasks:
    - name: cloning repo
      shell: git clone git@github.com:VlN9/Wagtail-web.git

    - name: configure database
      shell: cd /home/ec2-user/Wagtail-web/ && ./dump.sh 

    - name: deploy application
      shell: cd /home/ec2-user/Wagtail-web && docker-compose up -d --build
